In [5]:
import numpy as np 
import pandas as pd

#### read data

In [6]:
df_test = pd.read_csv('./test.csv', header = None)
df_train = pd.read_csv('./train.csv', header = None)
df_train_label = pd.read_csv('./trainLabels.csv', header = None)

In [7]:
df_test.head()

0         1         2         3         4         5         6   \
0  2.808909 -0.242894 -0.546421  0.255162  1.749736 -0.030458 -1.322071   
1 -0.374101  0.537669  0.081063  0.756773  0.915231  2.557282  3.703187   
2 -0.088370  0.154743  0.380716 -1.176126  1.699867 -0.258627 -1.384999   
3 -0.685635  0.501283  1.873375  0.215224 -3.983468 -0.103637  4.136113   
4  0.350867  0.721897 -0.477104 -1.748776 -2.627405  1.075433  4.954253   

         7         8         9   ...        30        31        32        33  \
0  3.578071 -0.667578 -0.884257  ... -0.261688 -0.224375 -1.675606 -0.479584   
1  1.673835 -0.764122 -1.228040  ... -0.969463  0.574154 -2.200519 -1.612240   
2  1.093584  1.596633  0.230631  ... -0.769885 -0.005143  1.467490  0.483803   
3 -0.225431 -1.515015 -1.071763  ...  0.968609  2.386412 -0.131219  0.285646   
4 -3.293501 -0.760369  0.204360  ...  0.260553 -2.045650 -2.173227  0.372992   

         34        35        36        37        38        39  
0 -0.244388 -0.672355  0.517860  0.010665 -0.419214  2.818387  
1  0.179031 -2.924596  0.643610 -1.470939 -0.067408 -0.976265  
2 -3.542981  0.814561 -1.652948  1.265866 -1.749248  1.773784  
3  2.302069  1.255588 -1.563090 -0.125258 -1.030761 -2.945329  
4  0.450700 -0.211657  1.301359 -0.522164  2.484883  0.039213  

[5 rows x 40 columns]

In [8]:
df_train.head()

0         1         2         3         4         5         6   \
0  0.299403 -1.226624  1.498425 -1.176150  5.289853  0.208297  2.404498   
1 -1.174176  0.332157  0.949919 -1.285328  2.199061 -0.151268 -0.427039   
2  1.192222 -0.414371  0.067054 -2.233568  3.658881  0.089007  0.203439   
3  1.573270 -0.580318 -0.866332 -0.603812  3.125716  0.870321 -0.161992   
4 -0.613071 -0.644204  1.112558 -0.032397  3.490142 -0.011935  1.443521   

         7         8         9   ...        30        31        32        33  \
0  1.594506 -0.051608  0.663234  ... -0.850465 -0.622990 -1.833057  0.293024   
1  2.619246 -0.765884 -0.093780  ... -0.819750  0.012037  2.038836  0.468579   
2 -4.219054 -1.184919 -1.240310  ... -0.604501  0.750054 -3.360521  0.856988   
3  4.499666  1.038741 -1.092716  ...  1.022959  1.275598 -3.480110 -1.065252   
4 -4.290282 -1.761308  0.807652  ...  0.513906 -1.803473  0.518579 -0.205029   

         34        35        36        37        38        39  
0  3.552681  0.717611  3.305972 -2.715559 -2.682409  0.101050  
1 -0.517657  0.422326  0.803699  1.213219  1.382932 -1.817761  
2 -2.751451 -1.582735  1.672246  0.656438 -0.932473  2.987436  
3  2.153133  1.563539  2.767117  0.215748  0.619645  1.883397  
4 -4.744566 -1.520015  1.830651  0.870772 -1.894609  0.408332  

[5 rows x 40 columns]

In [9]:
df_train_label.head()

0
0  1
1  0
2  0
3  1
4  0

#### data preprocess

In [12]:
#from sklearn.model_selection import train_test_split
#x_train,x_test,y_train,y_test = train_test_split(df_train, df_train_label, train_size = 0.8)
#x_train.shape,x_test.shape,y_train.shape,y_test.shape

((800, 40), (200, 40), (800, 1), (200, 1))

#### classification

In [21]:
# random forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
rf_clf = RandomForestClassifier()
train_label_arr = np.squeeze(df_train_label) # change into 1d
scores = cross_val_score(rf_clf, df_train, train_label_arr, cv=5, scoring='accuracy')
print(scores)
print(scores.mean())

[0.89  0.885 0.885 0.88  0.845]
0.877


In [22]:
# GBDT
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score
gb_clf = GradientBoostingClassifier()
train_label_arr = np.squeeze(df_train_label) # change into 1d
scores = cross_val_score(gb_clf, df_train, train_label_arr, cv=5, scoring='accuracy')
print(scores)
print(scores.mean())

[0.87  0.885 0.865 0.84  0.85 ]
0.8619999999999999


In [25]:
# LR
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
lr = LogisticRegression()
train_label_arr = np.squeeze(df_train_label) # change into 1d
scores = cross_val_score(lr, df_train, train_label_arr, cv=5, scoring='accuracy')
print(scores)
print(scores.mean())

[0.835 0.855 0.82  0.79  0.8  ]
0.82


In [31]:
# XGB
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score
xgb_clf = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
train_label_arr = np.squeeze(df_train_label) # change into 1d
scores = cross_val_score(xgb_clf, df_train, train_label_arr, cv=5, scoring='accuracy')
print(scores)
print(scores.mean())

[0.91  0.9   0.875 0.88  0.865]
0.8859999999999999


#### classification - normalization 

In [33]:
from sklearn.preprocessing import StandardScaler, Normalizer
norm = Normalizer()
df_norm_train = norm.fit_transform(df_train)

In [34]:
# random forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
rf_clf = RandomForestClassifier()
train_label_arr = np.squeeze(df_train_label) # change into 1d
scores = cross_val_score(rf_clf, df_norm_train, train_label_arr, cv=5, scoring='accuracy')
print(scores)
print(scores.mean())

[0.89  0.88  0.875 0.84  0.865]
0.8699999999999999


In [35]:
# GBDT
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score
gb_clf = GradientBoostingClassifier()
train_label_arr = np.squeeze(df_train_label) # change into 1d
scores = cross_val_score(gb_clf, df_norm_train, train_label_arr, cv=5, scoring='accuracy')
print(scores)
print(scores.mean())

[0.885 0.87  0.885 0.865 0.845]
0.8699999999999999


In [36]:
# LR
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
lr = LogisticRegression()
train_label_arr = np.squeeze(df_train_label) # change into 1d
scores = cross_val_score(lr, df_norm_train, train_label_arr, cv=5, scoring='accuracy')
print(scores)
print(scores.mean())

[0.825 0.87  0.81  0.815 0.805]
0.825


In [37]:
# XGB
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score
xgb_clf = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
train_label_arr = np.squeeze(df_train_label) # change into 1d
scores = cross_val_score(xgb_clf, df_norm_train, train_label_arr, cv=5, scoring='accuracy')
print(scores)
print(scores.mean())

[0.895 0.895 0.91  0.88  0.865]
0.889


#### final - XGB + normalization

In [44]:
xgb_clf.fit(df_norm_train, train_label_arr)
pred  = xgb_clf.predict(df_test)
xgb_clf_pred = pd.DataFrame(pred)

In [45]:
xgb_clf_pred.columns = ['Solution']
xgb_clf_pred['Id'] = np.arange(1,xgb_clf_pred.shape[0]+1)
xgb_clf_pred = xgb_clf_pred[['Id', 'Solution']]
xgb_clf_pred.to_csv('Submission_nor_XGB.csv',index=False)

In [46]:
xgb_clf_pred

Id  Solution
0        1         1
1        2         0
2        3         0
3        4         0
4        5         0
...    ...       ...
8995  8996         1
8996  8997         1
8997  8998         0
8998  8999         0
8999  9000         0

[9000 rows x 2 columns]